blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Documentation
    url: https://github.com/AshDevFr/latex-cookbook-template/blob/main/DOCUMENTATION.md
    about: Check the documentation for usage instructions and examples
